package Database;

public class Table {

    public static String[] getInit() {
        String init = ""
                + "CREATE TABLE IF NOT EXISTS USERS ("
                + "    email varchar(255) NOT NULL,"
                + "    PRIMARY KEY (email),"
                + "    password varchar(255) NOT NULL,"
                + "    name varchar(255) NOT NULL,"
                + "    phone varchar(255) NOT NULL,"
                + "    ubication varchar(255) NOT NULL"
                + ");"
                + "CREATE TABLE IF NOT EXISTS PUBLICATIONS ("
                + "    title varchar(255) NOT NULL,"
                + "    PRIMARY KEY (title),"
                + "    description varchar(255) NOT NULL,"
                + "    date date NOT NULL,"
                + "    photo text NOT NULL,"
                + "    condition STICKERS_PUBLICATIONS_CONDITIONS NOT NULL,"
                + "    email varchar(255) NOT NULL,"
                + "    FOREIGN KEY (email) REFERENCES USERS(email)"
                + ");"
                + "CREATE TABLE IF NOT EXISTS STICKERS ("
                + "    player varchar(255),"
                + "    country varchar(255) NOT NULL,"
                + "    number varchar(255) NOT NULL,"
                + "    CONSTRAINT PK_Sticker PRIMARY KEY (country, number),"
                + "    photo text"
                + ");"
                + "CREATE TABLE IF NOT EXISTS STICKER_PUBLICATIONS("
                + "    title varchar(255) NOT NULL,"
                + "    FOREIGN KEY (title) REFERENCES PUBLICATIONS(title),"
                + "    PRIMARY KEY(title),"
                + "    country varchar(255) NOT NULL,"
                + "    number varchar(255) NOT NULL,"
                + "    FOREIGN KEY (country, number) REFERENCES STICKERS(country, number)"
                + ");"
                + "CREATE TABLE IF NOT EXISTS USERS_STICKERS("
                + "    quantity smallint NOT NULL,"
                + "    email varchar(255) NOT NULL,"
                + "    FOREIGN KEY (email) REFERENCES USERS(email),"
                + "    country varchar(255) NOT NULL,"
                + "    number varchar(255) NOT NULL,"
                + "    FOREIGN KEY (country, number) REFERENCES STICKERS(country, number),"
                + "    CONSTRAINT PK_Users_Stickers PRIMARY KEY (email, country, number)"
                + ");"
                + "CREATE TABLE IF NOT EXISTS PUBLICATION_LOOKSFOR("
                + "    title varchar(255) NOT NULL,"
                + "    FOREIGN KEY (title) REFERENCES PUBLICATIONS(title),"
                + "    country varchar(255) NOT NULL,"
                + "    number varchar(255) NOT NULL,"
                + "    FOREIGN KEY (country, number) REFERENCES STICKERS(country, number),"
                + "    CONSTRAINT PK_Publication_LooksFor PRIMARY KEY (title, country, number)"
                + ");"
                + "CREATE TABLE IF NOT EXISTS OFFERS("
                + "    title varchar(255) NOT NULL,"
                + "    state OFFERS_TYPE NOT NULL,"
                + "    description varchar(255) NOT NULL,"
                + "    date date NOT NULL,"
                + "    email varchar(255) NOT NULL,"
                + "    FOREIGN KEY (email) REFERENCES USERS(email),"
                + "    related_title varchar(255) NOT NULL,"
                + "    FOREIGN KEY (related_title) REFERENCES PUBLICATIONS(title),"
                + "    CONSTRAINT PK_Offers PRIMARY KEY (title)"
                + ");"
                + "CREATE TABLE IF NOT EXISTS OFFERS_STICKERS("
                + "    offer_title varchar(255) NOT NULL,"
                + "    FOREIGN KEY (offer_title) REFERENCES OFFERS(title),"
                + "    country varchar(255) NOT NULL,"
                + "    number varchar(255) NOT NULL,"
                + "    FOREIGN KEY (country, number) REFERENCES STICKERS(country, number),"
                + "    CONSTRAINT PK_Offers_Stickers PRIMARY KEY(offer_title, number, country)"
                + ");";
        return init.split(";");
    }
}
